---
- block:
  # root

  - name: "Set shutdown timeout"
    lineinfile:
      path: /etc/systemd/system.conf
      regexp: '^.*DefaultTimeoutStopSec=.*$'
      line: "DefaultTimeoutStopSec={{ systemd_default_timeout_stop_sec }}"

  - name: "Create /etc/systemd/journald.conf.d"
    file:
      path: /etc/systemd/journald.conf.d
      state: directory
      group: root

  - name: "Forwarding the journal to /dev/tty12"
    copy:
      dest: "/etc/systemd/journald.conf.d/fw-tty12.conf"
      content: |
        [Journal]
        ForwardToConsole=yes
        TTYPath=/dev/tty12
        MaxLevelConsole=info

  become: true
