---
- block:
  # root

  - name: "Create the chroot wrapper"
    copy:
      dest: "/tmp/chroot_wrapper"
      mode: 0755
      content: |
        #!/bin/sh -e
        exec arch-chroot {{ install_path }} /usr/bin/python3 "$@"

  - name: "Create /tmp/ansible on host"
    file:
      path: "/tmp/ansible"
      state: 'directory'
      mode: 0777

  - name: "Create /tmp/ansible in chroot"
    file:
      path: "{{ install_path }}/tmp/ansible"
      state: 'directory'
      mode: 0777

  - name: "Bindmount /tmp/ansible to chroot for temporary ansible file transfers"
    ansible.posix.mount:
      path: "{{ install_path }}/tmp/ansible"
      src: "/tmp/ansible"
      opts: rbind
      state: mounted
      fstype: none

  become: true
