---
- block:
  # root

  - name: "Create /etc/hostname"
    shell:
      cmd: |
        echo "{{ hostname }}" > /etc/hostname
    args:
      executable: /bin/bash

  - name: "Create /etc/hosts"
    shell:
      cmd: |
        cat > /etc/hosts <<INEOF
        127.0.0.1     localhost.localdomain   localhost
        ::1           localhost.localdomain   localhost
        127.0.0.1     {{ hostname }}.local   {{ hostname }}
        INEOF
    args:
      executable: /bin/bash

  - name: 'Install NetworkManager'
    package:
      name:
        - networkmanager
        - net-tools
      state: latest

  - name: 'Enable networkmanager service'
    systemd:
      name: 'NetworkManager'
      enabled: 'yes'

  - name: 'Enable systemd-resolved service'
    systemd:
      name: 'systemd-resolved'
      enabled: 'yes'

  become: true
