---
- block:
  # root

  - name: "Create /etc/hostname"
    copy:
      dest: "/etc/hostname"
      content: |
        {{ hostname }}

  - name: "Create /etc/hosts"
    copy:
      dest: "/etc/hosts"
      content: |
        127.0.0.1     localhost.localdomain   localhost
        ::1           localhost.localdomain   localhost
        127.0.0.1     {{ hostname }}.local   {{ hostname }}

  - name: 'Install NetworkManager'
    package:
      name:
        - networkmanager
        - net-tools
      state: latest

  - name: 'Enable networkmanager service'
    systemd:
      name: "{{ item }}"
      enabled: 'yes'
    with_items:
      - "NetworkManager"
      - "systemd-resolved"

  become: true
