---
- block:
  # root

  - name: "Get /sys/firmware/efi/efivars"
    stat:
      path: "/sys/firmware/efi/efivars"
    register: efivars

  - name: "Throw error if not booted in EFI mode"
    fail:
      msg: "Not running in EFI mode"
    when: not efivars.stat.exists

  - name: "Print distribution information"
    debug:
      var: ansible_facts['distribution']

  become: true
