- block:
  - name: "Check for ADM CPU"
    lineinfile:
      path: /proc/cpuinfo
      regexp: '.*AMD.*'
      state: absent
    check_mode: yes
    register: amd_cpu

  - name: "Check for Intel CPU"
    lineinfile:
      path: /proc/cpuinfo
      regexp: '.*Intel.*'
      state: absent
    check_mode: yes
    register: intel_cpu

  - name: "Set fact has_amd_cpu"
    set_fact:
      has_amd_cpu: "{{ amd_cpu.found > 0 }}"

  - name: "Set fact has_intel_cpu"
    set_fact:
      has_intel_cpu: "{{ intel_cpu.found > 0 }}"

  - name: "Show has_intel_cpu fact"
    debug:
      var: has_intel_cpu

  - name: "Show has_amd_cpu fact"
    debug:
      var: has_amd_cpu

- block:
  # superuser

  - name: "Create data partition on {{ install_device }}"
    community.general.parted:
      device: "/dev/{{ install_device }}"
      name: "data"
      label: gpt
      number: 3
      part_type: primary
      state: present
      part_start: "{{ root_partition_end }}"
      part_end: "100%"

  # longhorn reuires a ext4 filesystem (btrfs is currently not supported)
  # for now we test with unencrypted data partition
  - name: "Create ext4 Filesystem"
    community.general.filesystem:
      fstype: ext4
      dev: "/dev/disk/by-partlabel/data"
      force: true

  become: true
  when: create_data_partition

- block:
  # superuser

  - name: "Create /etc/nixos"
    file:
      path: "{{ install_path }}/etc/nixos"
      state: 'directory'
      mode: 0755

  - name: "Create /etc/nixos/config"
    file:
      path: "{{ install_path }}/etc/nixos/config"
      state: 'directory'
      mode: 0755

  - name: "Create /etc/secrets/initrd"
    file:
      path: "{{ install_path }}/etc/secrets/initrd"
      state: 'directory'
      mode: 0755

  - name: "Copy disk key"
    copy:
      src: "{{ install_path }}{{ luks_keyfile }}"
      dest: "{{ install_path }}/etc/secrets/initrd{{ luks_keyfile }}"
      owner: root
      group: root
      mode: '0000'
      remote_src: yes

  - name: "Create NixOS hardware-config"
    template:
      src: hardware-configuration.nix.j2
      dest: "{{ install_path }}/etc/nixos/hardware-configuration.nix"
      owner: root
      group: root
      mode: 0755

  - name: "Create NixOS config entrypoint"
    template:
      src: configuration.nix.j2
      dest: "{{ install_path }}/etc/nixos/configuration.nix"
      owner: root
      group: root
      mode: 0755

  - name: "Create NixOS minimal config"
    template:
      src: config/configuration.nix.j2
      dest: "{{ install_path }}/etc/nixos/config/configuration.nix"
      owner: root
      group: root
      mode: 0755

  - name: "Install NixOS"
    shell:
      cmd: nixos-install --root {{ install_path }}
      chdir: "{{ install_path }}"

  become: true

