---
- block:
  # root

  - name: 'Install base packages for paru'
    package:
      name:
        - openssl
        - rustup
      state: latest

  # - name: 'rustup install stable for {{ username }} user'
  #   command:
  #     cmd: "su -c 'rustup install stable' -s /bin/sh {{ username }}"

  # - name: 'rustup set stable as default for {{ username }} user'
  #   command:
  #     cmd: "su -c 'rustup default stable' -s /bin/sh {{ username }}"

  # - name: 'clone https://aur.archlinux.org/paru.git'
  #   command:
  #     cmd: "su -c 'git clone https://aur.archlinux.org/paru.git /home/{{ username }}/.cache/paru/clone/paru' -s /bin/sh {{ username }}"
  #   ignore_errors: true

  - name: 'clone https://aur.archlinux.org/paru-bin.git'
    command:
      cmd: "su -c 'git clone https://aur.archlinux.org/paru-bin.git /home/{{ username }}/.cache/paru/clone/paru' -s /bin/sh {{ username }}"
    ignore_errors: true

  - name: "Set system MAKEFLAGS"
    lineinfile:
      path: /etc/makepkg.conf
      regexp: '^#MAKEFLAGS=.*$'
      line: 'MAKEFLAGS="-j$(expr $(nproc) + 1)"'

  - name: 'Build paru (this may take some time)'
    command:
      cmd: "su -c 'cd /home/{{ username }}/.cache/paru/clone/paru && makepkg --noconfirm -f -s && cd -' -s /bin/sh {{ username }}"

  - name: 'Install paru'
    shell:
      cmd: |
        pacman --noconfirm --needed -U /home/{{ username }}/.cache/paru/clone/paru/paru-*.pkg.tar.zst

  become: true
