---
- block:

  - name: "Create user group audit"
    group:
      name: audit
      state: present

  - name: "Create user group sshusers"
    group:
      name: sshusers
      state: present

  - name: "Create user {{ username }}"
    user:
      name: "{{ username }}"
      shell: /bin/bash
      groups: wheel,audio,video,uucp,audit,sshusers,users
      append: yes
      password: "{{ user_password | password_hash('sha512') }}"
      create_home: yes

  - name: 'Install xdg-user-dirs'
    package:
      name:
        - xdg-user-dirs
      state: latest

  - name: "Generate xdg user dirs"
    command:
      cmd: "su -c 'xdg-user-dirs-update --force' -s /bin/sh {{ username }}"

  - name: "Generate user directories"
    command:
      cmd: "su -c 'mkdir -p /home/{{ username }}/{{ item }}' -s /bin/sh {{ username }}"
    with_items:
      - ".ssh"
      - ".cache"

  - name: "Add wheel group to sudoers"
    lineinfile:
      path: /etc/sudoers.d/11-user
      line: 'wheel ALL=(ALL:ALL) ALL'
      create: yes
      validate: 'visudo -cf %s'

  become: true
