---
- block:

  - name: "Create user group audit"
    group:
      name: audit
      state: present

  - name: "Create user {{ username }}"
    user:
      name: "{{ username }}"
      shell: /bin/bash
      groups: wheel,audio,video,uucp,audit,users
      append: yes
      password: "{{ user_password | password_hash('sha512') }}"

  - name: 'Install xdg-user-dirs'
    package:
      name:
        - xdg-user-dirs
      state: latest

  - name: "Generate xdg user dirs"
    command:
      cmd: "su -c 'xdg-user-dirs-update --force' -s /bin/sh {{ username }}"

  become: true
