---
- block:

  - name: 'Install ssh server'
    package:
      name:
        - openssh
      state: latest

  - name: "Adjust ssh server config"
    lineinfile:
      path: "/etc/ssh/sshd_config"
      line: "{{ item }}"
    with_items:
      - "DenyUsers root"
      - "DenyGroups root"
      - "AllowGroups sshusers"

  - name: 'Enable ssh server service'
    systemd:
      name: 'sshd'
      enabled: 'yes'

  when: enable_ssh_server
  become: true
