---
- block:
  # root

  - name: "Set root_dev = /dev/mapper/{{ crypt_label_sys }}"
    set_fact:
      root_dev: "/dev/mapper/{{ crypt_label_sys }}"
    when: enable_encryption

  - name: "Set root_dev = /dev/disk/by-partlabel/{{ part_label_root }}"
    set_fact:
      root_dev: "/dev/disk/by-partlabel/{{ part_label_root }}"
    when: not enable_encryption

  - name: 'Install dosfstools'
    package:
      name:
        - dosfstools
      state: latest
    when: ansible_facts['distribution'] != "NixOS"

  - name: "Create vfat Filesystem"
    community.general.filesystem:
      fstype: vfat
      dev: "/dev/disk/by-partlabel/{{ part_label_boot }}"
      opts: "-F 32"
      force: true

  - name: "Create btrfs Filesystem"
    community.general.filesystem:
      fstype: btrfs
      dev: "{{ root_dev }}"
      opts: "-L {{ btrfs_label_root }}"
      force: true

  - name: "Create mount point for btrfs root volume"
    file:
      path: '{{ tmp_btrfs_root_mount_path }}'
      state: 'directory'
      owner: '0'
      group: '0'
      mode: '0755'

  - name: "Mount btrfs root volume"
    mount:
      path: "{{ tmp_btrfs_root_mount_path }}"
      src: "LABEL={{ btrfs_label_root }}"
      fstype: 'btrfs'
      opts: '{{ btrfs_mount_opts }}'
      state: "mounted"
      fstab: /tmp/tmp.fstab

  - name: "Create btrfs subvolumes"
    command: "btrfs subvolume create \"{{ tmp_btrfs_root_mount_path }}/{{ item.name }}\""
    loop: "{{ btrfs_subvolumes }}"

  - name: NixOS options
    block:

    - name: "Mount tmpfs root volume"
      mount:
        path: "{{ install_path }}"
        src: "tmpfs"
        fstype: 'tmpfs'
        opts: 'defaults,size=2G,mode=755'
        state: "mounted"
        fstab: /tmp/tmp.fstab
      when: tmpfs_root

    when: ansible_facts['distribution'] == "NixOS"

  - name: "Mount btrfs subvolumes"
    include_tasks: mount_btrfs_subvolume.yml
    vars:
      mount_path: "{{ install_path }}{{ item.path }}"
      btrfs_subvolume: "{{ item.name }}"
    loop: "{{btrfs_subvolumes}}"

  - name: "Create mount point for {{ install_path }}/boot/efi"
    file:
      path: '{{ install_path }}/boot/efi'
      state: 'directory'
      owner: '0'
      group: '0'
      mode: '0755'

  - name: "Mount vfat /dev/disk/by-partlabel/{{ part_label_boot }} partition"
    mount:
      path: "{{ install_path }}/boot/efi"
      src: "/dev/disk/by-partlabel/{{ part_label_boot }}"
      fstype: 'vfat'
      state: "mounted"
      fstab: /tmp/tmp.fstab

  - name: "Get /dev/disk/by-partlabel/{{ part_label_boot }} UUID"
    shell:
      cmd: "blkid /dev/disk/by-partlabel/{{ part_label_boot }} -s UUID -o value"
    register: boot_uuid_info

  - name: "Create var boot_uuid"
    set_fact:
      boot_uuid: "{{ boot_uuid_info.stdout }}"

  - name: "Get {{ root_dev }} UUID"
    shell:
      cmd: "blkid {{ root_dev }} -s UUID -o value"
    register: btrfs_root_uuid_info

  - name: "Create var btrfs_root_uuid"
    set_fact:
      btrfs_root_uuid: "{{ btrfs_root_uuid_info.stdout }}"

  - name: "Create /etc"
    file:
      path: "{{ install_path }}/etc"
      state: 'directory'
      owner: '0'
      group: '0'

  - name: "Create fstab"
    template:
      src: fstab.j2
      dest: "{{ install_path }}/etc/fstab"
      owner: root
      group: root
      mode: 0644
    when: generate_fstab

  become: true
