hostname: "nixos"
username: "nix"
generate_fstab: False
create_ext4_data_partition: True

luks_keyfile: "/boot/disk.key"
btrfs_subvolumes:
  - name: "@"
    path: "/"
  - name: "@nix"
    path: "/nix"
  - name: "@home"
    path: "/home"
  - name: "@opt"
    path: "/opt"
  - name: "@log"
    path: "/var/log"
  - name: "@swap"
    path: "/swap"

# I do not recommend root on tmpfs unless you have several hundret of GB RAM!
tmpfs_root: False
# tmpfs root:
# btrfs_subvolumes:
#   - name: "@boot"
#     path: "/boot"
#   - name: "@nix"
#     path: "/nix"
#   - name: "@home"
#     path: "/home"
#   - name: "@opt"
#     path: "/opt"
