---
- block:
  # root

  - name: 'Install mkinitcpio'
    package:
      name:
        - mkinitcpio
      state: latest

  - name: "Set /etc/mkinitcpio.conf HOOKS"
    ansible.builtin.lineinfile:
      path: /etc/mkinitcpio.conf
      regexp: '^HOOKS='
      line: "HOOKS=( base udev autodetect modconf block keyboard keymap encrypt btrfs filesystems fsck )"

  - name: "Set /etc/mkinitcpio.conf MODULES"
    ansible.builtin.lineinfile:
      path: /etc/mkinitcpio.conf
      regexp: '^MODULES='
      line: "MODULES=( crc32c vfio_pci vfio vfio_iommu_type1 vfio_virqfd )"

  - name: "Set /etc/mkinitcpio.conf FILES"
    ansible.builtin.lineinfile:
      path: /etc/mkinitcpio.conf
      regexp: '^FILES='
      line: "FILES=( {{ luks_keyfile }} )"
    when: enable_encryption

  - name: "Generate inital ramdisk"
    command:
      cmd: "mkinitcpio -P"

  # TODO why does this fail?
  # - name: "Set permissions for initramfs to 0600"
  #   file:
  #     dest: "{{ item }}"
  #     mode: "0600"
  #   with_fileglob:
  #   - "/boot/initramfs-linux*"
  #   ignore_errors: true

  become: true
