---
- block:
  # root

  - name: 'Install cryptsetup'
    package:
      name:
        - cryptsetup
      state: latest
    when: ansible_facts['distribution'] != "NixOS"

  - name: "Ensure to recreate LUKS container {{ crypt_label_sys }}"
    community.crypto.luks_device:
      device: "/dev/disk/by-partlabel/{{ part_label_root }}"
      state: "absent"
      name: "{{ crypt_label_sys }}"
    ignore_errors: true

  - name: "Create LUKS container {{ crypt_label_sys }} for {{ part_label_root }}"
    community.crypto.luks_device:
      device: "/dev/disk/by-partlabel/{{ part_label_root }}"
      state: "opened"
      name: "{{ crypt_label_sys }}"
      passphrase: "{{ luks_passphrase }}"
      hash: "sha512"
      type: luks1
      pbkdf:
        iteration_count: "{{ luks_pbkdf_iterations }}"

  become: true
  when: enable_encryption
