---
- block:
  # root

  - name: 'Install cryptsetup'
    package:
      name:
        - cryptsetup
      state: latest

  - name: "Remove LUKS container {{ crypt_dev_label }}"
    community.crypto.luks_device:
      device: "/dev/disk/by-partlabel/{{ part_label_root }}"
      state: "absent"
      name: "{{ crypt_dev_label }}"
    when: not vagrant|default(False) == True

  - name: "Create LUKS container {{ crypt_dev_label }} for {{ part_label_root }}"
    community.crypto.luks_device:
      device: "/dev/disk/by-partlabel/{{ part_label_root }}"
      state: "opened"
      name: "{{ crypt_dev_label }}"
      passphrase: "{{ luks_passphrase }}"
      hash: "sha512"
      type: luks1
      pbkdf:
        iteration_count: "{{ luks_pbkdf_iterations }}"


  become: true
