generate_fstab: True
tmp_btrfs_root_mount_path: "/tmp/btrfs-root"
tmpfs_root: False
btrfs_mount_opts: "defaults,ssd,noatime,compress=zstd"
btrfs_subvolumes:
  - name: "@"
    path: "/"
  - name: "@snapshots"
    path: "/.snapshots"
  - name: "@swap"
    path: "/swap"
  - name: "@home"
    path: "/home"
  - name: "@log"
    path: "/var/log"
  - name: "@docker"
    path: "/opt/docker"
  - name: "@libvirt"
    path: "/var/lib/libvirt/images"
  - name: "@nix"
    path: "/nix"

